### ISSUE TITLE
creates empty directory "Codes"

### ISSUE THREAD

**Issue by goswami-rahul** [vampire-slayer/Codeforces-Solutions-Downloader#1]
I think, it is something to do with `fix.c`.  https://github.com/vampire-slayer/Codeforces-Solutions-Downloader/blob/3e74ae11c1101a75c91e4e2bdebe912a9987f0ce/fix.c#L59-L61 
The `if` condition is never satisfied, and the code doesn't enter that part, when I tried to download using this script. I think the CF format has changed or some other problem.

**Comment by vampire-slayer** [comment]
The format of the CF solution page has changed it seems. I have made the change accordingly.
